#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    blogApp-phpmyadmin-80-http:
      entrypoints:
        - http-8036
      rule: HostRegexp(`^blogapp\.ddev\.site$`)
      
      service: "blogApp-phpmyadmin-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "blogApp-redirectHttps"
    blogApp-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^blogapp\.ddev\.site$`)
      
      service: "blogApp-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "blogApp-redirectHttps"
    blogApp-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^blogapp\.ddev\.site$`)
      
      service: "blogApp-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "blogApp-redirectHttps"
    
    
    blogApp-phpmyadmin-80-https:
      entrypoints:
        - http-8037
      rule: HostRegexp(`^blogapp\.ddev\.site$`)
      
      service: "blogApp-phpmyadmin-80"
      ruleSyntax: v3
      
      tls: true
      
    
    
    blogApp-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^blogapp\.ddev\.site$`)
      
      service: "blogApp-web-80"
      ruleSyntax: v3
      
      tls: true
      
    blogApp-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^blogapp\.ddev\.site$`)
      
      service: "blogApp-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    blogApp-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    blogApp-phpmyadmin-80:
      loadbalancer:
        servers:
          - url: http://ddev-blogApp-phpmyadmin:80
        
    
    blogApp-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-blogApp-web:80
        
    blogApp-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-blogApp-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/blogApp.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/blogApp.key